# Exception handling

> **Python Exception hierarchy**
> 
> https://docs.python.org/3/library/exceptions.html#exception-hierarchy

## The try and except Blocks
- The order of `except` blocks matters. <br>If you define `except Exeption` above `except NameError` and NameError error occures, the **except Exception** block will be executed, and try-catch block will be closed. However Python requires the `except` block to be the last one in the list.  

```python
# Example 1
try:
    print(variable)
except Exception:
    print("")
except NameError:
    print("Variable is not defined") # This will be printed
except:           # Can only be the last value in try-catch
    print("Something went wrong") 

# Example 2
try:
    print(variable)
except Exception:
    print("Something went wrong") # This will be executed
except NameError:
    print("Variable is not defined")
except:
    print("Something went wrong")
```


## Defining Custom Exception Handlers

```python
atempts = 0

while True:
    try:
        input_var = input("Please enter a number: ")
        input_var = int(input_var)
        break
    
    except ValueError:
        attempts += 1

        if attempts < 3:
            print("Opps! That was not a valid number. Try again . . .")
        else:
            print("You really want to input a string! Fine we'll handle it")
            input_var = str(input_var)
            break
```

## The Exception Hierarchy

```python
import time, datetime

try:
    print(datetime.datetime.now())
    time.sleep(5)
    print(datetime.datetime.now())

except KeyboardInterrupt:
    print("Process has been manually canceled")

```
### Exception with file handling

```python
try:
    file = open("non_existen_file", "r")
except OSError:
    print("OSError occured") # Superset of FileNotFoundError
except FileNotFoundError:
    print("File does not exist") # Subset of OSError

```

### Open not existing variable
```python
try:
    print(var)
except NameError:
    print("Variable name")
finally:
    print("Gracefully exiting the try-except-finally block")

var = "Hello there"

try:
    print(var)
except NameError:
    print("Variable name")
finally:
    print("Gracefully exiting the try-except-finally block")
```

### Omitting the except block
- If any error occures within the try block, finally block will not be executed. You need to catch error and then finally will execute.
- If no error occures in try block, then finally will be executed. 
- In the example below, **finally** block is used to close the file.

```python
try:
    file = open('../TEST/Linux/test.py', "r")
    print(file.read())
finally:
    print("Closing the file")
    file.close()
    print(f"File closed : {file.closed}")
```

## Chaining except Blocks

```python
try:
    file=open("testfile.txt")
    file.write ("Writing to the open file")
except:
    print("Oops! Something went wrong")
else:
    print("Nothing went wrong")

```


## Exception Payloads




## Creating New Exceptions




## Assertions




## 






